---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EC2AccessS3RoleParam:
    Type: String
    Description: Role Name
    Default: EC2-Access-S3-Role
  InstanceProfileNameParam:
    Type: String
    Description: Instance Profile Name
    Default: EC2-Access-S3-Instance-Profile
  S3BucketName:
    Type: String
    Description: Bucket Name
    Default: emp-bucket
  S3PolicyName:
    Type: String
    Description: S3 Policy Name
    Default: S3-Policy
Resources:
  EC2AccessS3Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Ref EC2AccessS3RoleParam
      Path: /
  S3Policy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Ref S3PolicyName
      Description: S3 Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: S3Access
            Effect: Allow
            Action:
              - 's3:List*'
              - 's3:GetObject'
            Resource:
              - !Sub 'arn:aws:s3:::*${S3BucketName}*'
      Roles:
        - Ref: EC2AccessS3Role
  EC2AccessS3InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Ref InstanceProfileNameParam
      Path: "/"
      Roles:
      - Ref: EC2AccessS3Role
