AWSTemplateFormatVersion: 2010-09-09
Parameters:
  LambdaAccessRDSRoleParam:
    Type: String
    Description: Name of the role
    Default: Lambda-Access-RDS-Role
  RDSPolicyName:
    Type: String
    Description: Name of the RDS policy name
    Default: RDS-Policy
Resources:
  LambdaAccessRDSRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Ref LambdaAccessRDSRoleParam
      Path: /
  RDSPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Ref RDSPolicyName
      Description: Policy for RDS access
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: RDSAccess
            Effect: Allow
            Action:
              - 'rds:StartDBCluster'
              - 'rds:StopDBCluster'
            Resource:
              - !Sub 'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:*'
      Roles:
        - Ref: LambdaAccessRDSRole
