---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Launch an EC2 Instance."
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0b44050b2d893d5f7"
      InstanceType: "t2.micro"
      #SubnetId: "subnet-cec2ae82"
      AvailabilityZone: "ap-south-1b"
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeType: "gp2"
            #DeleteOnTerminaction: "true"
            VolumeSize: "10"
      Tags:
        - Key: "Name"
          Value: "Jenkins Server"
        - Key: "Tech_Owner_Mail"
          Value: "balaji.pothula@techie.com"
      #SecurityGroupIds: ["sg-cc2fcdae"]
      KeyName: EC2
      #DisableApiTermination: "true"
      InstanceInitiatedShutdownBehavior: "stop"
      Monitoring: "false"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          GroupSet: ["sg-cc2fcdae"]
          SubnetId: "subnet-cec2ae82"
